# 文件名: .github/workflows/sync-ttyd.yml

name: Sync ttyd Image to My Docker Hub

# 这个 workflow 的触发条件
on:
  # 1. 允许手动触发 (在 Actions 页面会有一个 'Run workflow' 按钮)
  workflow_dispatch:

  # 2. (可选) 定时触发，使用 cron 语法
  # 下面的例子是每天凌晨3点（UTC时间）运行一次
  # 如果你不需要定时同步，可以把整个 'schedule' 部分删除或注释掉
  schedule:
    - cron: '0 3 * * *'

jobs:
  sync-image:
    # 使用最新的 Ubuntu 系统作为运行环境
    runs-on: ubuntu-latest

    steps:
      # 第一步: 登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3 # 使用官方的登录 action
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # 使用我们刚设置的 secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # 使用我们刚设置的 secret

      # 第二步: 拉取、打标签、推送
      - name: Pull, Tag, and Push Docker Image
        run: |
          # 定义源镜像和目标镜像
          # 你可以修改这里的标签，比如 'latest' 或者一个具体的版本号 '1.7.4'
          SOURCE_IMAGE="tsl0922/ttyd:latest"
          TARGET_IMAGE="lbzt/ttyd:latest"

          # 打印信息，方便调试
          echo "--- Syncing Docker Image ---"
          echo "Source: ${SOURCE_IMAGE}"
          echo "Target: ${TARGET_IMAGE}"

          # 执行核心命令
          docker pull ${SOURCE_IMAGE}
          docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}
          docker push ${TARGET_IMAGE}
          
          echo "--- Sync complete! ---"
